all:

  children:

    veeam_server:

      hosts:

        backup01:

          ansible_host: 192.168.161.145

          ansible_user: Administrator

    veeam_targets:

      hosts:

        target01:

          ansible_host: 192.168.161.143

          ansible_user: Administrator
