---
all:
  children:
    veeam_server:
      hosts:
        vbr01:
          ansible_host: 192.168.161.145     
          ansible_user: Administrator
          ansible_password: "{{ vault_win_admin_password }}"
          ansible_connection: winrm
          ansible_winrm_transport: ntlm
          ansible_winrm_server_cert_validation: ignore
          ansible_port: 5985

    targets:
      hosts:
        win_target_01:
          ansible_host: 192.168.161.146   # WIN-N09EOQN5PFF
          ansible_user: Administrator
          ansible_password: "{{ vault_win_admin_password }}"
          ansible_connection: winrm
          ansible_winrm_transport: ntlm
          ansible_winrm_server_cert_validation: ignore
          ansible_port: 5985
