targets:

  - hostname: WIN-N09EOQN5PFF

    ip_address: 192.168.161.144

    deploy_vdk: true

    protection_group:

      name: Veeam_Target

      auth_method: certificate

    backup_job:

      name: Veeam_Target_Backup

      type: server

      mode: managed_by_backup_server

      backup_mode: entire_computer

      repository: Default Backup Repository

      retention_days: 7

      application_aware_processing: true

      run_after_create: true


sql:

  installer_path: C:\Installers\SQLEXPR_x64_ENU\setup.exe

  instance_name: VEEAMSQL2022

  instance_id: VEEAMSQL2022

  sql_service_name: MSSQL$VEEAMSQL2022

  sql_browser_service: SQLBrowser


vbr:

  hostname: WIN-2JS87DVNUFR

  setup_path: C:\Veeam\Veeam

  silent_installer: C:\Veeam\Veeam\Setup\Veeam.Silent.Install.exe

  answer_file: C:\Temp\VBRAnswer.xml

  log_folder: C:\Temp\VeeamLogs

  repository: Default Backup Repository
