---
- name: Install SQL Server
  hosts: all
  gather_facts: false

  vars_files:
    - ../vars/veeam_config.yml

  tasks:

    - name: Include SQL Role
      include_role:
        name: veeam_sql_install
