---
- name: Full Veeam Onboarding Workflow
  hosts: all
  gather_facts: false

  vars_files:
    - ../vars/veeam_config.yml

- import_playbook: deploy_vdk.yml

- import_playbook: create_protection_group.yml

- import_playbook: create_backup_job.yml

- import_playbook: run_backup.yml
